# Generated by Django 5.0.6 on 2024-05-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django')], max_length=70),
        ),
    ]
