# Generated by Django 5.0.6 on 2024-05-15 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 5, 47, 24, 720921, tzinfo=datetime.timezone.utc)),
        ),
    ]
