# Generated by Django 5.0.6 on 2024-05-15 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_alter_article_pub_date_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 6, 4, 1, 499710, tzinfo=datetime.timezone.utc)),
        ),
    ]
