# Generated by Django 5.0.6 on 2024-05-15 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 6, 30, 33, 312778, tzinfo=datetime.timezone.utc)),
        ),
    ]
