# Generated by Django 5.0.6 on 2024-05-16 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 1, 35, 1, 514144, tzinfo=datetime.timezone.utc)),
        ),
    ]
