# Generated by Django 5.0.6 on 2024-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_message_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='age',
        ),
    ]
